name: tests

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn
  
      - name: run unit tests
        run: yarn test:unit
  integration-tests:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_DATABASE: test-todo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      DBHOST: mongo
      DBPORT: 27017
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: run unit tests
        run: yarn test:integration
  