name: tests

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn
  
      - name: run unit tests
        run: yarn test:unit
  integration-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: heakthcheck/mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: test-todo
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: test
    
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: run integration tests
        run: yarn test:integration
        env:
          DBHOST: mongodb
          DBPORT: ${{ job.services.mongodb.ports[27017] }}
  